export const DATE_FORMAT = {
  DATE: 'DD/MM/YYYY',
  DATE_TIME: 'DD/MM/YYYY HH:mm',
  DATE_TIME_SECOND: 'DD/MM/YYYY HH:mm:ss',
  DATE_TIME_MILLISECOND: 'DD/MM/YYYY HH:mm:ss.SSS',
  TIME: 'HH:mm',
  TIME_SECOND: 'HH:mm:ss',
  TIME_MILLISECOND: 'HH:mm:ss.SSS'
}
